version: "3.7"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data